#ifndef PYTHONAPICODES_H
#define PYTHONAPICODES_H

static const int CHANGE_DATA_COLLECTION_PATH = 4020;
static const int ENABLE_SENSOR_DATA_COLLECTION = 4021;
static const int DISABLE_SENSOR_DATA_COLLECTION = 4022;
static const int START_RECORDING_REQUEST = 4023;
static const int STOP_RECORDING_REQUEST = 4024;

#endif // PYTHONAPICODES_H
