/*  Copyright (c) 2023, Beamagine

    Permission is hereby granted, free of charge, to any person obtaining a copy
    of this software and associated documentation files (the "Software"), to deal
    in the Software without restriction, including without limitation the rights
    to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
    copies of the Software, and to permit persons to whom the Software is
    furnished to do so, subject to the following conditions:

    The Software may only be used in combination with Beamagine products.

    The above copyright notice and this permission notice shall be included in all
    copies or substantial portions of the Software.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
    OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
    SOFTWARE.
*/

/*
LIST OF BEAMAGINE ERRORS
*/

#define L3CAM_OK    0

//!INTERNAL ERRORS
#define L3CAM_NO_SENSORS_AVAILABLE              11
#define L3CAM_INVALID_PARAMETERS                12

#define L3CAM_TIMEOUT_ERROR                     210
#define L3CAM_ERROR_OUT_OF_MEMORY               211

#define L3CAM_UNDEFINED_SENSOR                  222
#define L3CAM_VALUE_OUT_OF_RANGE                223
#define L3CAM_SENSOR_NOT_AVAILABLE              224
#define L3CAM_FORBIDEN_SENSOR                   225

#define L3CAM_ERROR_CREATING_TCP_CLIENT_SOCKET  230
#define L3CAM_ERROR_INITALIZING_WSA             231
#define L3CAM_ERROR_CONNECTING_WITH_TCP_SERVER  232
#define L3CAM_ERROR_SENDING_TCP_MESSAGE         233
#define L3CAM_ERROR_CREATING_TCP_SERVER_SOCKET  234
#define L3CAM_ERROR_BINDING_SOCKET              235
#define L3CAM_ERROR_STARTING_TCP_SERVER         236
#define L3CAM_ERROR_ACCEPTING_TCP_CLIENT        237

//!LIDAR ERRORS

//!ECON CAMERA ERRORS
#define ERROR_OPENING_ECON_CAMERA               20
#define ERROR_SETTING_ECON_CAMERA_PARAMETER     21
#define ERROR_SETTING_ECON_DEFAULT              22


//!POLARIMETRIC ERRORS
#define ERROR_POL_STD_EXCEPTION             300
#define ERROR_POL_RUNTIME_EXCEPTION         301
#define ERROR_POL_GENERIC_EXCEPTION         302
#define ERROR_POL_TIMEOUT_EXCEPTION         303
#define ERROR_POL_UNDEFINED_ERROR           304
#define ERROR_POL_PERCEPTION_EXCEPTION      305

//!THERMAL ERRORS
#define ERROR_OPENING_THERMAL_CAMERA    400
#define ERROR_THERMAL_IMAGE_SIZE        401
#define ERROR_CLOSING_THERMAL_CAMERA    402
#define ERROR_SETTING_THERMAL_LUT       403
#define ERROR_GETTING_THERMAL_LUT       404
#define ERROR_SETTING_THERMAL_SHARPEN   405
#define ERROR_SETTING_THERMAL_SMOOTH    406
#define ERROR_GETTING_THERMAL_SYSTEM    407
#define ERROR_SETTING_THERMAL_SYSTEM    408

//!ALLIED CAMERAS ERRORS
#define ERROR_ALLIED_PARAMETER_NOT_DEFINED                      500
#define ERROR_ALLIED_BLACK_LEVEL_NOT_AVAILABLE                  501
#define ERROR_ALLIED_CONFIGURING_BLACK_LEVEL                    502
#define ERROR_ALLIED_CONFIGURING_EXPOSURE_TIME                  503
#define ERROR_ALLIED_EXPOSURE_TIME_NOT_AVAILABLE                504
#define ERROR_ALLIED_CONFIGURUNG_AUTO_EXPOSURE_TIME             505
#define ERROR_ALLIED_AUTO_EXPOSURE_TIME_NOT_AVAILABLE           506
#define ERROR_ALLIED_CONFIGURING_AUTO_EXPOSURE_RANGE_MAX        507
#define ERROR_ALLIED_AUTO_EXPOSURE_MAX_NOT_AVAILABLE            508
#define ERROR_ALLIED_CONFIGURING_AUTO_EXPOSURE_RANGE_MIN        509
#define ERROR_ALLIED_AUTO_EXPOSURE_MIN_NOT_AVAILABLE            510
#define ERROR_ALLIED_CONFIGURING_GAIN                           511
#define ERROR_ALLIED_GAIN_NOT_AVAILABLE                         512
#define ERROR_ALLIED_CONFIGURUNG_AUTO_GAIN                      513
#define ERROR_ALLIED_AUTO_GAIN_NOT_AVAILABLE                    514
#define ERROR_ALLIED_CONFIGURING_AUTO_GAIN_RANGE_MAX            515
#define ERROR_ALLIED_AUTO_GAIN_MAX_NOT_AVAILABLE                516
#define ERROR_ALLIED_CONFIGURING_AUTO_GAIN_RANGE_MIN            517
#define ERROR_ALLIED_AUTO_GAIN_MIN_NOT_AVAILABLE                518
#define ERROR_ALLIED_CONFIGURING_GAMMA                          519
#define ERROR_ALLIED_GAMMA_NOT_AVAILABLE                        520
#define ERROR_ALLIED_CONFIGURING_SATURATION                     521
#define ERROR_ALLIED_SATURATION_NOT_AVAILABLE                   522
#define ERROR_ALLIED_CONFIGURING_SHARPNESS                      523
#define ERROR_ALLIED_SHARPNESS_NOT_AVAILABLE                    524
#define ERROR_ALLIED_CONFIGURING_HUE                            525
#define ERROR_ALLIED_HUE_NOT_AVAILABLE                          526
#define ERROR_ALLIED_CONFIGURING_INTENSITY_AUTO_PRECEDENCE      527
#define ERROR_ALLIED_INTENSITY_AUTO_PRECEDENCE_NOT_AVAILABLE    528
#define ERROR_ALLIED_CONFIGURING_BALANCE_RATIO_SELECTOR         529
#define ERROR_ALLIED_BALANCE_RATIO_SELECTOR_NOT_AVAILABLE       530
#define ERROR_ALLIED_CONFIGURING_BALANCE_RATIO                  531
#define ERROR_ALLIED_BALANCE_RATIO_NOT_AVAILABLE                532
#define ERROR_ALLIED_CONFIGURUNG_AUTO_BALANCE_WHITE             533
#define ERROR_ALLIED_AUTO_BALANCE_WHITE_NOT_AVAILABLE           534
#define ERROR_ALLIED_CONFIGURING_BALANCE_WHITE_AUTO_RATE        535
#define ERROR_ALLIED_BALANCE_WHITE_AUTO_RATE_NOT_AVAILABLE      536
#define ERROR_ALLIED_CONFIGURING_WHITE_AUTO_TOLERANCE           537
#define ERROR_ALLIED_WHITE_AUTO_TOLERANCE_NOT_AVAILABLE         538
#define ERROR_ALLIED_CONFIGURING_AUTO_MODE_REGION_HEIGHT        539
#define ERROR_ALLIED_AUTO_MODE_REGION_HEIGHT_NOT_AVAILABLE      540
#define ERROR_ALLIED_CONFIGURING_AUTO_MODE_REGION_WIDTH         541
#define ERROR_ALLIED_AUTO_MODE_REGION_WIDTH_NOT_AVAILABLE       542
#define ERROR_ALLIED_CONFIGURING_INTENSITY_CONTROLLER_REGION    543
#define ERROR_ALLIED_INTENSITY_CONTROLLER_REGION_NOT_AVAILABLE  544
#define ERROR_ALLIED_CONFIGURING_INTENSITY_CONTROLLER_TARGET    545
#define ERROR_ALLIED_INTENSITY_CONTROLLER_TARGET_NOT_AVAILABLE  546
#define ERROR_ALLIED_CONFIGURING_MAX_DRIVER_BUFFERS_COUNT       547
#define ERROR_ALLIED_MAX_DRIVER_BUFFERS_COUNT_NOT_AVAILABLE     548


